-- DEV SEED: see fail on tahtlikult tühi tootmiskeskkonnas.
-- Arenduskeskkonna testkasutaja lisamiseks kasuta:
--   backend/src/main/resources/db/seed/dev_seed.sql
-- (käivita käsitsi, mitte Flyway kaudu)
