package me.storyfor.backend.service;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.io.font.constants.StandardFonts;
import me.storyfor.backend.entity.Story;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

@Service
public class PdfService {

    public byte[] generatePdf(Story story) {
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            PdfWriter writer = new PdfWriter(baos);
            PdfDocument pdf = new PdfDocument(writer);
            Document doc = new Document(pdf, PageSize.A5);
            doc.setMargins(50, 40, 50, 40);

            PdfFont titleFont = PdfFontFactory.createFont(StandardFonts.TIMES_BOLD);
            PdfFont bodyFont = PdfFontFactory.createFont(StandardFonts.TIMES_ROMAN);

            doc.add(new Paragraph(story.getTitle())
                    .setFont(titleFont).setFontSize(22)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(20));

            doc.add(new Paragraph("A bedtime story")
                    .setFont(bodyFont).setFontSize(12)
                    .setFontColor(ColorConstants.GRAY)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(30));

            String[] paragraphs = story.getContent().split("\n\n");
            for (String para : paragraphs) {
                if (!para.isBlank()) {
                    doc.add(new Paragraph(para.trim())
                            .setFont(bodyFont).setFontSize(13)
                            .setMultipliedLeading(1.5f)
                            .setMarginBottom(12));
                }
            }

            doc.add(new Paragraph("~ The End ~")
                    .setFont(bodyFont).setFontSize(14)
                    .setFontColor(ColorConstants.GRAY)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginTop(30));

            doc.add(new Paragraph("Generated by StoryFor.me")
                    .setFont(bodyFont).setFontSize(9)
                    .setFontColor(ColorConstants.LIGHT_GRAY)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginTop(20));

            doc.close();
            return baos.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("PDF generation failed", e);
        }
    }
}
